# Generated by Django 4.2.18 on 2026-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('people_count', models.IntegerField()),
                ('estimated_wait_seconds', models.FloatField()),
                ('service_rate', models.FloatField(default=50.0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='queue_monit_timesta_a85f44_idx')],
            },
        ),
    ]
